#!/usr/bin/gawk -f

#
# this script collects the purchase information based on the 
# id of the purchaser and stores in into an array. it then prints
# each element of the array into a file
#
#



BEGIN {
FS=","
OFS=","
}

{
	if($6 != "")
	{
	array[$1] += $6 # total amount
	}
	array2[$1] = $12 #state
	array3[$1] = $13 #zip
	array4[$1] = $3 #last name
	array5[$1] = $2 #first name
	



}
END {
str=""
	for (i in array)
	{
		str=i","array2[i]","array3[i]","array4[i]","array5[i]","array[i]
		print str >> "tempsum"
	}


	#sort -k2,2 -k3,3 -k4,4 -k5,5 summary.csv

}



